### ISSUE TITLE
Question about final variables.

### ISSUE THREAD

**Issue by joshing-dev** [mealingr/2048-Java-Port#1]
I was reading through your code and was wondering why you declare so many variables? I have created a clone of 2048 in Java as well, but it is very inefficient because all it uses is a bunch of if and else control statements and puts JLabels in a multi-dimensional array.

**Comment by mealingr** [comment]
For the Game class the static final constants are about the game, but which could potentially be changed. They're just to remind the reader of the "classic" version. The Random variable is for experiments, so you can pass in your own Random with your own seed. The tiles (why add 2s and 4s?), probabilities (why 90% and 10%?) and winningTile (why 2048?) are all for customizing the game. The grid, bestScore, and score variables are needed to match the original, hasWon is for the benefit of the players. The Player variable is for the player implementation to get actions (currentPlayer was for synchronization in case someone changed the player mid game in the GUI), game is just for tracking the number of games played.

As for the GUI the constants are mainly just for making it look like the online version (I actually took the colors from the CSS of the original).

Anyway my style is generally to define constants about the game or GUI or player as static final (this is why most of them are prefixed with DEFAULT). Then let the user customize these values if they want to by optionally passing them into the constructor. This way, although I've called the project 2048, it could easily be modified for example to be a game of 4096 on a 5x5 grid.

I've tried to keep the game logic, player logic and GUI all separate, which also sometimes increases the number of variables but I think makes it easier to extend and modify. A downside of my project though is I'm not sure how to easily do animations in Java. It would definitely improve the GUI if I could add that in.

**Comment by joshing-dev** [comment]
Thank you for elaborating on my question. I plan on reading through your code logic and understanding how it works versus mine. And to improve the GUI I will try to improve that for you when I get the time, because I work with a lot of GUI's versus the logic aspect. I did notice that the menu items are grey which makes it kind of different to see that.
